version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env.developer
    environment:
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    volumes:
      - home-hab-pgdata:/var/lib/postgresql/data

volumes:
  home-hab-pgdata:
